/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ermss;

import ermss_popup.addcategory;
import ermss_panels.categoryCard;
import databaseconnection.DBConnect;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import databaseconnection.*;
import ermss_popup.*;

/**
 *
 * @author charl_pxdrf1n
 */
public class Mainframe extends javax.swing.JFrame {

    /**
     * Creates new form Mainframe
     */
    
    PreparedStatement pts;
     ResultSet rs;
    
    public Mainframe() {
        initComponents();
        
getCategoryList();
    }

    
    
    
    
    
    
    
    public void getCategoryList(){
    
    String get = "SELECT * FROM categories"; //step 1
        try {
            pts = DBConnect.getInstance().con.prepareStatement(get);
            
            rs = pts.executeQuery();
            
            for(int i = 0; rs.next(); i++){
            
            modCategoryCard(rs.getString(1), i);
            
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnl_navbar = new javax.swing.JPanel();
        Jlbl_dashboard = new javax.swing.JLabel();
        Jlbl_equipmanage = new javax.swing.JLabel();
        Jlbl_sales = new javax.swing.JLabel();
        Jlbl_registry = new javax.swing.JLabel();
        Jlbl_settings = new javax.swing.JLabel();
        Jlbl_accounts = new javax.swing.JLabel();
        jpnl_equipcategory = new javax.swing.JPanel();
        Jlbl_addcategory = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jpnl_categorylist = new javax.swing.JPanel();
        Jlbl_addequip = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jpnl_equipmentlist = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equipment renting management and sales system");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnl_navbar.setBackground(new java.awt.Color(220, 220, 220));
        jpnl_navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jlbl_dashboard.setBackground(new java.awt.Color(220, 220, 220));
        Jlbl_dashboard.setFont(new java.awt.Font("Eras Bold ITC", 0, 10)); // NOI18N
        Jlbl_dashboard.setForeground(new java.awt.Color(51, 51, 51));
        Jlbl_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/dashboard.png"))); // NOI18N
        Jlbl_dashboard.setText("DASHBOARD");
        Jlbl_dashboard.setOpaque(true);
        Jlbl_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_dashboardMouseExited(evt);
            }
        });
        jpnl_navbar.add(Jlbl_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 40));

        Jlbl_equipmanage.setBackground(new java.awt.Color(220, 220, 220));
        Jlbl_equipmanage.setFont(new java.awt.Font("Eras Bold ITC", 0, 10)); // NOI18N
        Jlbl_equipmanage.setForeground(new java.awt.Color(51, 51, 51));
        Jlbl_equipmanage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/cmralens.png"))); // NOI18N
        Jlbl_equipmanage.setText("EQUIPMENT MANAGEMENT");
        Jlbl_equipmanage.setOpaque(true);
        Jlbl_equipmanage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_equipmanageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_equipmanageMouseExited(evt);
            }
        });
        jpnl_navbar.add(Jlbl_equipmanage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 190, 40));

        Jlbl_sales.setBackground(new java.awt.Color(220, 220, 220));
        Jlbl_sales.setFont(new java.awt.Font("Eras Bold ITC", 0, 10)); // NOI18N
        Jlbl_sales.setForeground(new java.awt.Color(51, 51, 51));
        Jlbl_sales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/sales.png"))); // NOI18N
        Jlbl_sales.setText("SALES");
        Jlbl_sales.setOpaque(true);
        Jlbl_sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_salesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_salesMouseExited(evt);
            }
        });
        jpnl_navbar.add(Jlbl_sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 190, 40));

        Jlbl_registry.setBackground(new java.awt.Color(220, 220, 220));
        Jlbl_registry.setFont(new java.awt.Font("Eras Bold ITC", 0, 10)); // NOI18N
        Jlbl_registry.setForeground(new java.awt.Color(51, 51, 51));
        Jlbl_registry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/register.png"))); // NOI18N
        Jlbl_registry.setText("REGISTRY");
        Jlbl_registry.setOpaque(true);
        Jlbl_registry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_registryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_registryMouseExited(evt);
            }
        });
        jpnl_navbar.add(Jlbl_registry, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 190, 40));

        Jlbl_settings.setBackground(new java.awt.Color(220, 220, 220));
        Jlbl_settings.setFont(new java.awt.Font("Eras Bold ITC", 0, 10)); // NOI18N
        Jlbl_settings.setForeground(new java.awt.Color(51, 51, 51));
        Jlbl_settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/settings.png"))); // NOI18N
        Jlbl_settings.setText("SETTINGS");
        Jlbl_settings.setOpaque(true);
        Jlbl_settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_settingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_settingsMouseExited(evt);
            }
        });
        jpnl_navbar.add(Jlbl_settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 190, 40));

        Jlbl_accounts.setBackground(new java.awt.Color(220, 220, 220));
        Jlbl_accounts.setFont(new java.awt.Font("Eras Bold ITC", 0, 10)); // NOI18N
        Jlbl_accounts.setForeground(new java.awt.Color(51, 51, 51));
        Jlbl_accounts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/accountsman.png"))); // NOI18N
        Jlbl_accounts.setText("ACCOUNTS MANAGEMENT");
        Jlbl_accounts.setOpaque(true);
        Jlbl_accounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_accountsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_accountsMouseExited(evt);
            }
        });
        jpnl_navbar.add(Jlbl_accounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 190, 40));

        getContentPane().add(jpnl_navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 500));

        jpnl_equipcategory.setBackground(new java.awt.Color(204, 204, 204));
        jpnl_equipcategory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jlbl_addcategory.setBackground(new java.awt.Color(220, 220, 220));
        Jlbl_addcategory.setForeground(new java.awt.Color(51, 51, 51));
        Jlbl_addcategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/add.png"))); // NOI18N
        Jlbl_addcategory.setText("add category");
        Jlbl_addcategory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Jlbl_addcategory.setOpaque(true);
        Jlbl_addcategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jlbl_addcategoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_addcategoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_addcategoryMouseExited(evt);
            }
        });
        jpnl_equipcategory.add(Jlbl_addcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 100, 20));

        jLabel1.setBackground(new java.awt.Color(220, 220, 220));
        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("EQUIPMENT CATEGORY");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setOpaque(true);
        jpnl_equipcategory.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 60));

        Jpnl_categorylist.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Jpnl_categorylistLayout = new javax.swing.GroupLayout(Jpnl_categorylist);
        Jpnl_categorylist.setLayout(Jpnl_categorylistLayout);
        Jpnl_categorylistLayout.setHorizontalGroup(
            Jpnl_categorylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        Jpnl_categorylistLayout.setVerticalGroup(
            Jpnl_categorylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(Jpnl_categorylist);

        jpnl_equipcategory.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 710, 90));

        Jlbl_addequip.setBackground(new java.awt.Color(220, 220, 220));
        Jlbl_addequip.setForeground(new java.awt.Color(51, 51, 51));
        Jlbl_addequip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/add.png"))); // NOI18N
        Jlbl_addequip.setText("add equipment");
        Jlbl_addequip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Jlbl_addequip.setOpaque(true);
        Jlbl_addequip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jlbl_addequipMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_addequipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_addequipMouseExited(evt);
            }
        });
        jpnl_equipcategory.add(Jlbl_addequip, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 110, 20));

        jLabel3.setBackground(new java.awt.Color(220, 220, 220));
        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("EQUPIMENT LIST");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setOpaque(true);
        jpnl_equipcategory.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 710, 60));

        Jpnl_equipmentlist.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Jpnl_equipmentlistLayout = new javax.swing.GroupLayout(Jpnl_equipmentlist);
        Jpnl_equipmentlist.setLayout(Jpnl_equipmentlistLayout);
        Jpnl_equipmentlistLayout.setHorizontalGroup(
            Jpnl_equipmentlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        Jpnl_equipmentlistLayout.setVerticalGroup(
            Jpnl_equipmentlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(Jpnl_equipmentlist);

        jpnl_equipcategory.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 690, 270));

        getContentPane().add(jpnl_equipcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 710, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Jlbl_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_dashboardMouseEntered
        Jlbl_dashboard.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_Jlbl_dashboardMouseEntered

    private void Jlbl_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_dashboardMouseExited
        Jlbl_dashboard.setBackground(new Color(220,220,220));
    }//GEN-LAST:event_Jlbl_dashboardMouseExited

    private void Jlbl_equipmanageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_equipmanageMouseEntered
        Jlbl_equipmanage.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_Jlbl_equipmanageMouseEntered

    private void Jlbl_equipmanageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_equipmanageMouseExited
        Jlbl_equipmanage.setBackground(new Color(220,220,220));
    }//GEN-LAST:event_Jlbl_equipmanageMouseExited

    private void Jlbl_registryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_registryMouseEntered
        Jlbl_registry.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_Jlbl_registryMouseEntered

    private void Jlbl_registryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_registryMouseExited
        Jlbl_registry.setBackground(new Color(220,220,220));
    }//GEN-LAST:event_Jlbl_registryMouseExited

    private void Jlbl_salesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_salesMouseEntered
        Jlbl_sales.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_Jlbl_salesMouseEntered

    private void Jlbl_salesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_salesMouseExited
        Jlbl_sales.setBackground(new Color(220,220,220));
    }//GEN-LAST:event_Jlbl_salesMouseExited

    private void Jlbl_accountsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_accountsMouseEntered
        Jlbl_accounts.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_Jlbl_accountsMouseEntered

    private void Jlbl_accountsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_accountsMouseExited
        Jlbl_accounts.setBackground(new Color(220,220,220));
    }//GEN-LAST:event_Jlbl_accountsMouseExited

    private void Jlbl_settingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_settingsMouseEntered
        Jlbl_settings.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_Jlbl_settingsMouseEntered

    private void Jlbl_settingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_settingsMouseExited
        Jlbl_settings.setBackground(new Color(220,220,220));
    }//GEN-LAST:event_Jlbl_settingsMouseExited

    private void Jlbl_addcategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_addcategoryMouseClicked
        // 1. write the query command 2. prepare statement 3.execute
        
        addcategory category = new addcategory(this);
        category.setVisible(true);
        
    }//GEN-LAST:event_Jlbl_addcategoryMouseClicked

    private void Jlbl_addequipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_addequipMouseClicked

        addequipment newequip = new addequipment();

        newequip.setVisible(true);

    }//GEN-LAST:event_Jlbl_addequipMouseClicked

    private void Jlbl_addcategoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_addcategoryMouseEntered
        Jlbl_addcategory.setBackground(new Color(200, 200, 200));
    }//GEN-LAST:event_Jlbl_addcategoryMouseEntered

    private void Jlbl_addcategoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_addcategoryMouseExited
        Jlbl_addcategory.setBackground(new Color(220,220,220));
    }//GEN-LAST:event_Jlbl_addcategoryMouseExited

    private void Jlbl_addequipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_addequipMouseEntered
        Jlbl_addequip.setBackground(new Color(200, 200, 200));
    }//GEN-LAST:event_Jlbl_addequipMouseEntered

    private void Jlbl_addequipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_addequipMouseExited
        Jlbl_addequip.setBackground(new Color(220,220,220));
    }//GEN-LAST:event_Jlbl_addequipMouseExited

    public void modCategoryCard (String categoryName, int i){
    
        categoryCard details = new categoryCard();
        
        details.jlbl_categoryname.setText(categoryName);
        
        int col = i % 6;
        int row = i / 1;
        
        int x = col * 140;
        int y = row * 65;
        
        details.setBounds(x, 0, 140, 65);
        
        Jpnl_categorylist.add(details);
        
        int newWidth;
        if (col == 0){
        
            newWidth = 2;
        }else{
        newWidth = (i + 1) *140;
        
        }
        
        int numRows = ((i+1) + 1) / 1;
        Jpnl_categorylist.setPreferredSize(new Dimension(newWidth, 65));
        Jpnl_categorylist.revalidate();
        Jpnl_categorylist.repaint();
    
    }
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlbl_accounts;
    private javax.swing.JLabel Jlbl_addcategory;
    private javax.swing.JLabel Jlbl_addequip;
    private javax.swing.JLabel Jlbl_dashboard;
    private javax.swing.JLabel Jlbl_equipmanage;
    private javax.swing.JLabel Jlbl_registry;
    private javax.swing.JLabel Jlbl_sales;
    private javax.swing.JLabel Jlbl_settings;
    private javax.swing.JPanel Jpnl_categorylist;
    private javax.swing.JPanel Jpnl_equipmentlist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpnl_equipcategory;
    private javax.swing.JPanel jpnl_navbar;
    // End of variables declaration//GEN-END:variables
}
