/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package ermss;

import java.awt.Color;
import ermss_popup.*;

/**
 *
 * @author charl_pxdrf1n
 */
public class registrypanel extends javax.swing.JPanel {

    /** Creates new form registrypanel */
    public registrypanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jlbl_addrenter = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jlbl_addrenter.setBackground(new java.awt.Color(220, 220, 220));
        Jlbl_addrenter.setForeground(new java.awt.Color(51, 51, 51));
        Jlbl_addrenter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/add.png"))); // NOI18N
        Jlbl_addrenter.setText("add renter");
        Jlbl_addrenter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Jlbl_addrenter.setOpaque(true);
        Jlbl_addrenter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jlbl_addrenterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_addrenterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_addrenterMouseExited(evt);
            }
        });
        add(Jlbl_addrenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 100, 20));

        jLabel1.setBackground(new java.awt.Color(220, 220, 220));
        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("REGISTRY MANAGEMENT");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "first name", "last name", "contact no", "address", "remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 690, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void Jlbl_addrenterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_addrenterMouseClicked

        addrenter newrenter = new addrenter();
        
        newrenter.setSize(315, 490);
        newrenter.setLocationRelativeTo(null);
        
        newrenter.setVisible(true);
    }//GEN-LAST:event_Jlbl_addrenterMouseClicked

    private void Jlbl_addrenterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_addrenterMouseEntered
        Jlbl_addrenter.setBackground(new Color(200, 200, 200));
    }//GEN-LAST:event_Jlbl_addrenterMouseEntered

    private void Jlbl_addrenterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_addrenterMouseExited
        Jlbl_addrenter.setBackground(new Color(220,220,220));
    }//GEN-LAST:event_Jlbl_addrenterMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlbl_addrenter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
