/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ermss_panels;

import java.awt.Color;

/**
 *
 * @author charl_pxdrf1n
 */
public class categoryCard extends javax.swing.JPanel {

    /**
     * Creates new form categoryCard
     */
    public categoryCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbl_categoryname = new javax.swing.JLabel();
        jlbl_regunit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_categoryname.setBackground(new java.awt.Color(51, 51, 51));
        jlbl_categoryname.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        jlbl_categoryname.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_categoryname.setText("CAMERA");
        jlbl_categoryname.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlbl_categoryname.setOpaque(true);
        jlbl_categoryname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbl_categorynameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbl_categorynameMouseExited(evt);
            }
        });
        add(jlbl_categoryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        jlbl_regunit.setForeground(new java.awt.Color(51, 51, 51));
        jlbl_regunit.setText("5");
        add(jlbl_regunit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 20, -1));

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("No. of units:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        this.setBackground(new Color(220,220,220));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        this.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_formMouseExited

    private void jlbl_categorynameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_categorynameMouseEntered
        jlbl_categoryname.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_jlbl_categorynameMouseEntered

    private void jlbl_categorynameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_categorynameMouseExited
        jlbl_categoryname.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_jlbl_categorynameMouseExited

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jlbl_categoryname;
    public javax.swing.JLabel jlbl_regunit;
    // End of variables declaration//GEN-END:variables
}
