/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ermss_popup;
import databaseconnection.DBConnect;
import ermss.Mainframe;
import java.awt.Color;
import java.sql.PreparedStatement;





/**
 *
 * @author charl_pxdrf1n
 */
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
public class addcategory extends javax.swing.JFrame {

    /**
     * Creates new form addcategory
     */
    public addcategory() {
        initComponents();
    }
    
    
    
    
    Mainframe main;
    PreparedStatement pts;
    
    
    
    
    
    
    
        public addcategory(Mainframe main) {
        initComponents();
        
        this.main = main;
        
    }
        
        
        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_categoryname = new javax.swing.JTextField();
        jbtn_confirm = new javax.swing.JButton();
        jbtn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("add category");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(220, 220, 220));
        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("   ENTER CATEGORY NAME:");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 30));
        jPanel1.add(jtxt_categoryname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, -1));

        jbtn_confirm.setText("CONFIRM");
        jbtn_confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtn_confirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtn_confirmMouseExited(evt);
            }
        });
        jbtn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_confirmActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jbtn_cancel.setText("CANCEL");
        jbtn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtn_cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtn_cancelMouseExited(evt);
            }
        });
        jbtn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 120));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelActionPerformed

        this.dispose();
    }//GEN-LAST:event_jbtn_cancelActionPerformed

    private void jbtn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_confirmActionPerformed

            String  categoryname = jtxt_categoryname.getText();
        
        //insert the query
        String insert = "INSERT INTO categories (category_name) VALUES (?)";

        try {
            //prepare the query --- prepare the statement

            pts =  DBConnect.getInstance().con.prepareStatement(insert);
            
            pts.setString(1, categoryname);
            
            //execute the query
            
            boolean state = pts.execute();
            
            if(state == false){
            
            JOptionPane.showMessageDialog(this,"category added");
            
            jtxt_categoryname.setText("");
            
            main.getCategoryList();
            
            this.dispose();
            }
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(addcategory.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jbtn_confirmActionPerformed

    private void jbtn_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_cancelMouseEntered
        jbtn_cancel.setBackground(new Color(248, 131, 121));
    }//GEN-LAST:event_jbtn_cancelMouseEntered

    private void jbtn_cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_cancelMouseExited
        jbtn_cancel.setBackground(UIManager.getColor("Button.background"));
    }//GEN-LAST:event_jbtn_cancelMouseExited

    private void jbtn_confirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_confirmMouseEntered
        jbtn_confirm.setBackground(new Color(175, 225, 175));
    }//GEN-LAST:event_jbtn_confirmMouseEntered

    private void jbtn_confirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_confirmMouseExited
        jbtn_confirm.setBackground(UIManager.getColor("Button.background"));
    }//GEN-LAST:event_jbtn_confirmMouseExited

    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addcategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addcategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addcategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addcategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addcategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_cancel;
    private javax.swing.JButton jbtn_confirm;
    private javax.swing.JTextField jtxt_categoryname;
    // End of variables declaration//GEN-END:variables
}
