/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ermss_popup;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import databaseconnection.*;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.UIManager;


/**
 *
 * @author ACLCSlab1
 */
public class addequipment extends javax.swing.JFrame {

    /**
     * Creates new form addequipment
     */
    
    String speclist = null;
    PreparedStatement pts;
    
    String filename = null;
    byte[] photo = null;
    
    
    
    
    
    public addequipment() {
        initComponents();
    
    jtxt_modelID.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "model ID");
    jtxt_equipname.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "equipment name");
    jtxt_brandname.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "brand name");
    jtxt_specifications.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "add specifications");
    jtxt_quantity.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "quantityu");
    jtxt_rentingprice.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "renting price");
                        
    jtxa_notes.setLineWrap(true);
    jtxa_speclist.disable();
    
    }
    
            



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbl_prodimage = new javax.swing.JLabel();
        jlbl_uploadprodimage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxt_modelID = new javax.swing.JTextField();
        jtxt_rentingprice = new javax.swing.JTextField();
        jcmb_catname = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtxt_equipname = new javax.swing.JTextField();
        jtxt_brandname = new javax.swing.JTextField();
        jbt_addspec = new javax.swing.JButton();
        jtxt_specifications = new javax.swing.JTextField();
        jtxt_quantity = new javax.swing.JTextField();
        jbtn_confirm = new javax.swing.JButton();
        jbtn_cancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxa_notes = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxa_speclist = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("add equipment");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_prodimage.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_prodimage.setFont(new java.awt.Font("Eras Bold ITC", 0, 11)); // NOI18N
        jlbl_prodimage.setForeground(new java.awt.Color(153, 153, 153));
        jlbl_prodimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_prodimage.setText("product image");
        jlbl_prodimage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.add(jlbl_prodimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 150, 150));

        jlbl_uploadprodimage.setFont(new java.awt.Font("Eras Bold ITC", 0, 11)); // NOI18N
        jlbl_uploadprodimage.setForeground(new java.awt.Color(102, 102, 102));
        jlbl_uploadprodimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_uploadprodimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/addPhoto.png"))); // NOI18N
        jlbl_uploadprodimage.setText("upload product image");
        jlbl_uploadprodimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jlbl_uploadprodimage.setOpaque(true);
        jlbl_uploadprodimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbl_uploadprodimageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbl_uploadprodimageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbl_uploadprodimageMouseExited(evt);
            }
        });
        jPanel1.add(jlbl_uploadprodimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 150, 30));

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("notes");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 160, 20));

        jtxt_modelID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_modelIDActionPerformed(evt);
            }
        });
        jPanel1.add(jtxt_modelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 300, 30));

        jtxt_rentingprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_rentingpriceActionPerformed(evt);
            }
        });
        jPanel1.add(jtxt_rentingprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 180, 30));

        jcmb_catname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lens" }));
        jcmb_catname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmb_catnameActionPerformed(evt);
            }
        });
        jPanel1.add(jcmb_catname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 300, 30));

        jLabel4.setText(" category name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, 20));

        jtxt_equipname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_equipnameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxt_equipname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 300, 30));

        jtxt_brandname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_brandnameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxt_brandname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 300, 30));

        jbt_addspec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newIcons/add.png"))); // NOI18N
        jbt_addspec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbt_addspecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbt_addspecMouseExited(evt);
            }
        });
        jbt_addspec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_addspecActionPerformed(evt);
            }
        });
        jPanel1.add(jbt_addspec, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 50, 30));

        jtxt_specifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_specificationsActionPerformed(evt);
            }
        });
        jPanel1.add(jtxt_specifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 240, 30));

        jtxt_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_quantityActionPerformed(evt);
            }
        });
        jPanel1.add(jtxt_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 100, 30));

        jbtn_confirm.setText("confirm");
        jbtn_confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtn_confirmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtn_confirmMouseExited(evt);
            }
        });
        jbtn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_confirmActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 130, 30));

        jbtn_cancel.setText("cancel");
        jbtn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtn_cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtn_cancelMouseExited(evt);
            }
        });
        jbtn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 130, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 10, 320));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Eras Bold ITC", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("   equipment information");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 30));

        jLabel7.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("equipment specifications");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 160, 20));

        jtxa_notes.setColumns(20);
        jtxa_notes.setRows(5);
        jtxa_notes.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jtxa_notes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 180, -1));

        jtxa_speclist.setColumns(10);
        jtxa_speclist.setRows(5);
        jScrollPane2.setViewportView(jtxa_speclist);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 180, 150));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 10, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_modelIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_modelIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_modelIDActionPerformed

    private void jtxt_rentingpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_rentingpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_rentingpriceActionPerformed

    private void jcmb_catnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_catnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmb_catnameActionPerformed

    private void jtxt_equipnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_equipnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_equipnameActionPerformed

    private void jtxt_brandnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_brandnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_brandnameActionPerformed

    private void jtxt_specificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_specificationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_specificationsActionPerformed

    private void jtxt_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_quantityActionPerformed

    private void jbtn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_cancelActionPerformed

    
    
    
    
    
    
    
    private void jbtn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_confirmActionPerformed

        String modelID = jtxt_modelID.getText();
        String catname = jcmb_catname.getSelectedItem().toString();
        String equipname = jtxt_equipname.getText();
        String brandname = jtxt_brandname.getText();
        
        int quantity = 0; 
        double rentingprice = 0;
        
        if (jtxt_quantity.getText().isEmpty()){
        quantity = 0;
        rentingprice = 0;

        
        }else{
        
            quantity = Integer.parseInt(jtxt_quantity.getText());
            rentingprice = Double.parseDouble(jtxt_rentingprice.getText());
            
        }
        
         String notes = jtxa_notes.getText();

         if (modelID.isEmpty()||
                 catname.isEmpty()||
                 equipname.isEmpty()||
                 brandname.isEmpty()||
                 quantity == 0 ||
                 rentingprice == 0 ||
                 speclist.isEmpty()){
         
         JOptionPane.showMessageDialog(this, "pls fill all forms");
             
         }else{
         
             String newequip = "INSERT INTO equipment_info (model_id, category_name, equipment_name, brand_name, product_image, specificatuion, quantity, renting_price, notes ) VALUES (?,?,?,?,?,?,?,?,?)";
             
            try {
                pts = DBConnect.getInstance().con.prepareStatement(newequip);
                
                pts.setString(1, modelID);
                pts.setString(2, catname);
                pts.setString(3, equipname);
                pts.setString(4, brandname);
                pts.setBytes(5, photo);
                pts.setString(6, speclist);
                pts.setInt(7, quantity);
                pts.setDouble(8, rentingprice);
                pts.setString(9, notes);
                
                boolean state = pts.execute();
                
                if(state == false){
                    JOptionPane.showMessageDialog(this, "added successfully");
                    
                    jtxt_modelID.setText("");
                    jtxt_equipname.setText("");
                    jtxt_brandname.setText("");
                    jlbl_prodimage.setText("product image");
                    speclist = "";
                    
                    jtxt_quantity.setText("");
                    jtxt_rentingprice.setText("");
                    jtxa_speclist.setText("");
                    jtxa_notes.setText("");
                    
                    this.dispose();

                }
            } catch (SQLException ex) {
                Logger.getLogger(addequipment.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
    }//GEN-LAST:event_jbtn_confirmActionPerformed

    
    
    
    
    
    
    
    
    private void jbt_addspecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_addspecActionPerformed

        if(jtxt_specifications.getText().isEmpty()){
        
            JOptionPane.showMessageDialog(this, "please do not add blank fields");
            
        }else{
        
        if(jtxa_speclist.getText().equals("")){
        
            jtxa_speclist.setText(jtxt_specifications.getText());
        
            speclist = jtxt_specifications.getText();
            
        }else{
        
            jtxa_speclist.setText(jtxa_speclist.getText() + ", \n" + jtxt_specifications.getText());
        
            
            speclist = speclist + ", \n" + jtxt_specifications.getText();
        }
        
        jtxt_specifications.setText("");

        }
    }//GEN-LAST:event_jbt_addspecActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    private void jlbl_uploadprodimageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_uploadprodimageMouseClicked

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();

        BufferedImage bi;
        try {
            bi = ImageIO.read(new File(filename));
            Image img = bi.getScaledInstance(jlbl_prodimage.getWidth(), jlbl_prodimage.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            jlbl_prodimage.setIcon(icon);
            
            
            
        } catch (IOException ex) {
            Logger.getLogger(addequipment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        File image = new File(filename);
        FileInputStream fis;
        
        try {
            fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;){
            
                bos.write(buf, 0, readNum);
            
            }
            photo = bos.toByteArray();
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(addequipment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(addequipment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jlbl_uploadprodimageMouseClicked

    private void jbtn_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_cancelMouseEntered
        jbtn_cancel.setBackground(new Color(248, 131, 121));
    }//GEN-LAST:event_jbtn_cancelMouseEntered

    private void jbtn_cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_cancelMouseExited
        jbtn_cancel.setBackground(UIManager.getColor("Button.background"));
    }//GEN-LAST:event_jbtn_cancelMouseExited

    private void jbtn_confirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_confirmMouseEntered
        jbtn_confirm.setBackground(new Color(175, 225, 175));
    }//GEN-LAST:event_jbtn_confirmMouseEntered

    private void jbtn_confirmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_confirmMouseExited
        jbtn_confirm.setBackground(UIManager.getColor("Button.background"));
    }//GEN-LAST:event_jbtn_confirmMouseExited

    private void jbt_addspecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_addspecMouseEntered
        jbt_addspec.setBackground(new Color(240, 255, 255));
    }//GEN-LAST:event_jbt_addspecMouseEntered

    private void jbt_addspecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbt_addspecMouseExited
        jbt_addspec.setBackground(UIManager.getColor("Button.background"));
    }//GEN-LAST:event_jbt_addspecMouseExited

    private void jlbl_uploadprodimageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_uploadprodimageMouseEntered
        jlbl_uploadprodimage.setBackground(new Color(240, 255, 255));
    }//GEN-LAST:event_jlbl_uploadprodimageMouseEntered

    private void jlbl_uploadprodimageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_uploadprodimageMouseExited
        jlbl_uploadprodimage.setBackground(UIManager.getColor("Button.background"));
    }//GEN-LAST:event_jlbl_uploadprodimageMouseExited

    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addequipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addequipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addequipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addequipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addequipment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbt_addspec;
    private javax.swing.JButton jbtn_cancel;
    private javax.swing.JButton jbtn_confirm;
    private javax.swing.JComboBox<String> jcmb_catname;
    private javax.swing.JLabel jlbl_prodimage;
    private javax.swing.JLabel jlbl_uploadprodimage;
    private javax.swing.JTextArea jtxa_notes;
    private javax.swing.JTextArea jtxa_speclist;
    private javax.swing.JTextField jtxt_brandname;
    private javax.swing.JTextField jtxt_equipname;
    private javax.swing.JTextField jtxt_modelID;
    private javax.swing.JTextField jtxt_quantity;
    private javax.swing.JTextField jtxt_rentingprice;
    private javax.swing.JTextField jtxt_specifications;
    // End of variables declaration//GEN-END:variables
}
