/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ermss_popup;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author charl_pxdrf1n
 */
public class addrenter extends javax.swing.JFrame {

    /**
     * Creates new form addrenter
     */
    public addrenter() {
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jpnl_rentinginfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcmb_equipment = new javax.swing.JComboBox<>();
        jcmb_category = new javax.swing.JComboBox<>();
        jlbl_totalpayable = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbl_equipimage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxa_spec = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxt_eventinfo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxt_duedate = new javax.swing.JTextField();
        jlbl_borroweddate = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jbtn_totransum = new javax.swing.JButton();
        jbtn_backpersonalinfo = new javax.swing.JButton();
        jpnl_finalizedtransac = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxa_transummary = new javax.swing.JTextArea();
        jbtn_uploadcontract = new javax.swing.JButton();
        jlbl_contract = new javax.swing.JLabel();
        jtxt_payment = new javax.swing.JTextField();
        jbtn_backrentinfo = new javax.swing.JButton();
        jbtn_confirm = new javax.swing.JButton();
        jpnl_personalinfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_fname = new javax.swing.JTextField();
        jtxt_mname = new javax.swing.JTextField();
        jtxt_lname = new javax.swing.JTextField();
        jtxt_cnum = new javax.swing.JTextField();
        jtxt_mail = new javax.swing.JTextField();
        jtxt_address = new javax.swing.JTextField();
        jbtn_govidupload = new javax.swing.JButton();
        jlbl_govid = new javax.swing.JLabel();
        jbtn_cancel = new javax.swing.JButton();
        jbtn_torentinfo = new javax.swing.JButton();

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("renter");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnl_rentinginfo.setBackground(new java.awt.Color(204, 204, 204));
        jpnl_rentinginfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(220, 220, 220));
        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RENTING INFO");
        jLabel2.setToolTipText("");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setOpaque(true);
        jpnl_rentinginfo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 300, 40));

        jcmb_equipment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpnl_rentinginfo.add(jcmb_equipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 130, -1));

        jcmb_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpnl_rentinginfo.add(jcmb_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, -1));

        jlbl_totalpayable.setForeground(new java.awt.Color(102, 102, 102));
        jlbl_totalpayable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnl_rentinginfo.add(jlbl_totalpayable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 110, 20));

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("select category:");
        jpnl_rentinginfo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jlbl_equipimage.setForeground(new java.awt.Color(102, 102, 102));
        jlbl_equipimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_equipimage.setText("equipment image");
        jlbl_equipimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnl_rentinginfo.add(jlbl_equipimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 150));

        jtxa_spec.setColumns(20);
        jtxa_spec.setRows(5);
        jScrollPane1.setViewportView(jtxa_spec);

        jpnl_rentinginfo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 100, 140));

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("select equipment:");
        jpnl_rentinginfo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("specifications:");
        jpnl_rentinginfo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("due date:");
        jpnl_rentinginfo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jtxt_eventinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_eventinfoActionPerformed(evt);
            }
        });
        jpnl_rentinginfo.add(jtxt_eventinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 260, -1));

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("total payable:");
        jpnl_rentinginfo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jtxt_duedate.setText("due date");
        jtxt_duedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_duedateActionPerformed(evt);
            }
        });
        jpnl_rentinginfo.add(jtxt_duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 100, -1));

        jlbl_borroweddate.setForeground(new java.awt.Color(102, 102, 102));
        jlbl_borroweddate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnl_rentinginfo.add(jlbl_borroweddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 110, 20));

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("borrowed date:");
        jpnl_rentinginfo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jbtn_totransum.setText("next");
        jbtn_totransum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_totransumActionPerformed(evt);
            }
        });
        jpnl_rentinginfo.add(jbtn_totransum, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        jbtn_backpersonalinfo.setText("back");
        jbtn_backpersonalinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_backpersonalinfoActionPerformed(evt);
            }
        });
        jpnl_rentinginfo.add(jbtn_backpersonalinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        getContentPane().add(jpnl_rentinginfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 300, 450));

        jpnl_finalizedtransac.setBackground(new java.awt.Color(255, 255, 255));
        jpnl_finalizedtransac.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(220, 220, 220));
        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TRANSACTION SUMMARY");
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setOpaque(true);
        jpnl_finalizedtransac.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        jtxa_transummary.setColumns(20);
        jtxa_transummary.setRows(5);
        jScrollPane2.setViewportView(jtxa_transummary);

        jpnl_finalizedtransac.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 280, 250));

        jbtn_uploadcontract.setText("upload");
        jbtn_uploadcontract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_uploadcontractActionPerformed(evt);
            }
        });
        jpnl_finalizedtransac.add(jbtn_uploadcontract, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jlbl_contract.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnl_finalizedtransac.add(jlbl_contract, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 200, 20));

        jtxt_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_paymentActionPerformed(evt);
            }
        });
        jpnl_finalizedtransac.add(jtxt_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 280, -1));

        jbtn_backrentinfo.setText("back");
        jbtn_backrentinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_backrentinfoActionPerformed(evt);
            }
        });
        jpnl_finalizedtransac.add(jbtn_backrentinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 130, -1));

        jbtn_confirm.setText("confirm");
        jbtn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_confirmActionPerformed(evt);
            }
        });
        jpnl_finalizedtransac.add(jbtn_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 130, -1));

        getContentPane().add(jpnl_finalizedtransac, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 300, 450));

        jpnl_personalinfo.setBackground(new java.awt.Color(255, 255, 255));
        jpnl_personalinfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(220, 220, 220));
        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PERSONAL INFO");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setOpaque(true);
        jpnl_personalinfo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        jtxt_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_fnameActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jtxt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 280, -1));

        jtxt_mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_mnameActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jtxt_mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 280, -1));

        jtxt_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_lnameActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jtxt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 280, -1));

        jtxt_cnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_cnumActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jtxt_cnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 280, -1));

        jtxt_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_mailActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jtxt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 280, -1));

        jtxt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_addressActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jtxt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 280, -1));

        jbtn_govidupload.setText("upload");
        jbtn_govidupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_goviduploadActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jbtn_govidupload, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jlbl_govid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnl_personalinfo.add(jlbl_govid, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 200, 20));

        jbtn_cancel.setText("cancel");
        jbtn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jbtn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 130, -1));

        jbtn_torentinfo.setText("next");
        jbtn_torentinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_torentinfoActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jbtn_torentinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 130, -1));

        getContentPane().add(jpnl_personalinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_fnameActionPerformed

    private void jtxt_mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_mnameActionPerformed

    private void jtxt_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_lnameActionPerformed

    private void jtxt_cnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_cnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_cnumActionPerformed

    private void jtxt_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_mailActionPerformed

    private void jtxt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_addressActionPerformed

    private void jbtn_goviduploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_goviduploadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_goviduploadActionPerformed

    private void jbtn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelActionPerformed

        this.dispose();

    }//GEN-LAST:event_jbtn_cancelActionPerformed

    private void jbtn_torentinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_torentinfoActionPerformed

        this.setSize(615, 490);
        this.setLocationRelativeTo(null);
        this.revalidate(); //refresh main/frame
        this.repaint();

        disableComponents(jpnl_personalinfo, false);

    }//GEN-LAST:event_jbtn_torentinfoActionPerformed

    private void jtxt_duedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_duedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_duedateActionPerformed

    private void jtxt_eventinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_eventinfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_eventinfoActionPerformed

    private void jbtn_totransumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_totransumActionPerformed

        this.setSize(915, 490);
        this.setLocationRelativeTo(null);
        this.revalidate(); //refresh main/frame
        this.repaint();
        
        disableComponents(jpnl_rentinginfo, false);



    }//GEN-LAST:event_jbtn_totransumActionPerformed

    private void jbtn_backpersonalinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_backpersonalinfoActionPerformed

        this.setSize(315, 490);
        this.setLocationRelativeTo(null);
        this.revalidate(); //refresh main/frame
        this.repaint();

        disableComponents(jpnl_personalinfo, true);



             

    }//GEN-LAST:event_jbtn_backpersonalinfoActionPerformed

    private void jbtn_uploadcontractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_uploadcontractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_uploadcontractActionPerformed

    private void jtxt_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_paymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_paymentActionPerformed

    private void jbtn_backrentinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_backrentinfoActionPerformed

        this.setSize(615, 490);
        this.setLocationRelativeTo(null);
        this.revalidate(); //refresh main/frame
        this.repaint();
        
        disableComponents(jpnl_rentinginfo, true);


    }//GEN-LAST:event_jbtn_backrentinfoActionPerformed

    private void jbtn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_confirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_confirmActionPerformed

    
    
    
    //------------------- ASSIGNEMENT: PLACE HOLDERS
    
    public void disableComponents(JPanel currentPanel, boolean isEnabled){
        
        currentPanel.setEnabled(isEnabled);
        Component[] components = currentPanel.getComponents();
        
        for(Component comp : components){
        
            if (comp instanceof JPanel){
            
                disableComponents((JPanel)comp, isEnabled);
                
            }
            comp.setEnabled(isEnabled);    
        }

    }
    

   /* 
    public void setPanelEnabled (JPanel panel, boolean isEnabled) {
    Component[] components = panel.getComponents();
    for (Component component : components) {
        component.setEnabled(isEnabled);
        if (component instanceof JPanel) {
            setPanelEnabled((JPanel) component, isEnabled); // Recursive call for nested panels
        }
    }
}

*/
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addrenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addrenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addrenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addrenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addrenter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JButton jbtn_backpersonalinfo;
    private javax.swing.JButton jbtn_backrentinfo;
    private javax.swing.JButton jbtn_cancel;
    private javax.swing.JButton jbtn_confirm;
    private javax.swing.JButton jbtn_govidupload;
    private javax.swing.JButton jbtn_torentinfo;
    private javax.swing.JButton jbtn_totransum;
    private javax.swing.JButton jbtn_uploadcontract;
    private javax.swing.JComboBox<String> jcmb_category;
    private javax.swing.JComboBox<String> jcmb_equipment;
    private javax.swing.JLabel jlbl_borroweddate;
    private javax.swing.JLabel jlbl_contract;
    private javax.swing.JLabel jlbl_equipimage;
    private javax.swing.JLabel jlbl_govid;
    private javax.swing.JLabel jlbl_totalpayable;
    private javax.swing.JPanel jpnl_finalizedtransac;
    private javax.swing.JPanel jpnl_personalinfo;
    private javax.swing.JPanel jpnl_rentinginfo;
    private javax.swing.JTextArea jtxa_spec;
    private javax.swing.JTextArea jtxa_transummary;
    private javax.swing.JTextField jtxt_address;
    private javax.swing.JTextField jtxt_cnum;
    private javax.swing.JTextField jtxt_duedate;
    private javax.swing.JTextField jtxt_eventinfo;
    private javax.swing.JTextField jtxt_fname;
    private javax.swing.JTextField jtxt_lname;
    private javax.swing.JTextField jtxt_mail;
    private javax.swing.JTextField jtxt_mname;
    private javax.swing.JTextField jtxt_payment;
    // End of variables declaration//GEN-END:variables
}
