/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ermss_popup;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Component;
import javax.swing.JPanel;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import databaseconnection.*;
import ermss.*;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;





/**
 *
 * @author charl_pxdrf1n
 */
public class addrenter extends javax.swing.JFrame {

    /**
     * Creates new form addrenter
     */
    
    PreparedStatement pts;
    ResultSet rs;
    
    
    ArrayList<String> equipinfo = new ArrayList<>();
    double equiprentingprice;
    int equipquantity; // stores current equip in data base
    LocalDate duedate;
    String eventinfo;
    double change, totalpayable;
    public int rentquantity;
    DateTimeFormatter formatter;
    String borroweddate;
    
    byte [] equipImage = null;
    byte [] contractfile = null;
    byte[] uploadedDocu = null;

    
    ResultSet equiprs;
    //String LocalDate;



    
    ArrayList<String> personalInfo = new ArrayList<>();
   


  
    
    public addrenter() {
        initComponents();
  
            jtxt_fname.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "first name");
            jtxt_mname.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "middle name");
            jtxt_lname.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "last name");
            jtxt_cnum.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "contact number");
            jtxt_mail.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "gmail");
            jtxt_address.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "address");
            jlbl_govid.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "goverment ID");
            
            jtxa_spec.disable();
            jtxt_Quantity.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "quantity");
            jtxt_duedate.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "DD-MM-YYYY");
            jtxt_eventinfo.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "event information");
            jtxa_transummary.disable();
            
            jtxt_payment.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "payment");
        
            jcmb_equipment.removeAllItems();
            jcmb_category.removeAllItems();
            
            String getcategories = "SELECT * FROM categories";
            
        try {
            pts = DBConnect.getInstance().con.prepareStatement(getcategories);
            rs = pts.executeQuery();
            while(rs.next()){
            jcmb_category.addItem(rs.getString(1));
            
            }   
        } catch (SQLException ex) {
            Logger.getLogger(addrenter.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //comboActionListeners();
        
        comboActionListeners();
            
            
        //NO TIME AND DATE IS SHOWING--------------------------
        formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        LocalDate currentDate = LocalDate.now();
        borroweddate = currentDate.format(formatter);
        jlbl_borroweddate.setText(borroweddate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jpnl_rentinginfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcmb_equipment = new javax.swing.JComboBox<>();
        jcmb_category = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jlbl_equipimage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxa_spec = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxt_eventinfo = new javax.swing.JTextField();
        jtxt_duedate = new javax.swing.JTextField();
        jlbl_borroweddate = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jbtn_totransum = new javax.swing.JButton();
        jbtn_backpersonalinfo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jtxt_Quantity = new javax.swing.JTextField();
        jpnl_finalizedtransac = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxa_transummary = new javax.swing.JTextArea();
        jbtn_uploadcontract = new javax.swing.JButton();
        jlbl_contract = new javax.swing.JLabel();
        jtxt_payment = new javax.swing.JTextField();
        jbtn_backrentinfo = new javax.swing.JButton();
        jbtn_confirm = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jpnl_personalinfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_fname = new javax.swing.JTextField();
        jtxt_mname = new javax.swing.JTextField();
        jtxt_lname = new javax.swing.JTextField();
        jtxt_cnum = new javax.swing.JTextField();
        jtxt_mail = new javax.swing.JTextField();
        jtxt_address = new javax.swing.JTextField();
        jbtn_govidupload = new javax.swing.JButton();
        jlbl_govid = new javax.swing.JLabel();
        jbtn_cancel = new javax.swing.JButton();
        jbtn_torentinfo = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("renter");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnl_rentinginfo.setBackground(new java.awt.Color(204, 204, 204));
        jpnl_rentinginfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(220, 220, 220));
        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RENTING INFO");
        jLabel2.setToolTipText("");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setOpaque(true);
        jpnl_rentinginfo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 300, 40));

        jcmb_equipment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpnl_rentinginfo.add(jcmb_equipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 130, -1));

        jcmb_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpnl_rentinginfo.add(jcmb_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, -1));

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("select category:");
        jpnl_rentinginfo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jlbl_equipimage.setForeground(new java.awt.Color(102, 102, 102));
        jlbl_equipimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_equipimage.setText("equipment image");
        jlbl_equipimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnl_rentinginfo.add(jlbl_equipimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 150));

        jtxa_spec.setColumns(20);
        jtxa_spec.setRows(5);
        jScrollPane1.setViewportView(jtxa_spec);

        jpnl_rentinginfo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 100, 140));

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("select equipment:");
        jpnl_rentinginfo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("specifications:");
        jpnl_rentinginfo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("due date:");
        jpnl_rentinginfo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 60, -1));

        jtxt_eventinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_eventinfoActionPerformed(evt);
            }
        });
        jpnl_rentinginfo.add(jtxt_eventinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 130, 100));

        jtxt_duedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_duedateActionPerformed(evt);
            }
        });
        jpnl_rentinginfo.add(jtxt_duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 110, -1));

        jlbl_borroweddate.setForeground(new java.awt.Color(102, 102, 102));
        jlbl_borroweddate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnl_rentinginfo.add(jlbl_borroweddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, 20));

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("borrowed date:");
        jpnl_rentinginfo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jbtn_totransum.setText("next");
        jbtn_totransum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_totransumActionPerformed(evt);
            }
        });
        jpnl_rentinginfo.add(jbtn_totransum, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 110, -1));

        jbtn_backpersonalinfo.setText("back");
        jbtn_backpersonalinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_backpersonalinfoActionPerformed(evt);
            }
        });
        jpnl_rentinginfo.add(jbtn_backpersonalinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, -1));

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("quantity:");
        jpnl_rentinginfo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jtxt_Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_QuantityActionPerformed(evt);
            }
        });
        jpnl_rentinginfo.add(jtxt_Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 110, -1));

        getContentPane().add(jpnl_rentinginfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 300, 450));

        jpnl_finalizedtransac.setBackground(new java.awt.Color(255, 255, 255));
        jpnl_finalizedtransac.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(220, 220, 220));
        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TRANSACTION SUMMARY");
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setOpaque(true);
        jpnl_finalizedtransac.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        jtxa_transummary.setColumns(20);
        jtxa_transummary.setRows(5);
        jScrollPane2.setViewportView(jtxa_transummary);

        jpnl_finalizedtransac.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 280, 250));

        jbtn_uploadcontract.setText("upload");
        jbtn_uploadcontract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_uploadcontractActionPerformed(evt);
            }
        });
        jpnl_finalizedtransac.add(jbtn_uploadcontract, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 80, -1));

        jlbl_contract.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnl_finalizedtransac.add(jlbl_contract, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 140, 22));

        jtxt_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_paymentActionPerformed(evt);
            }
        });
        jpnl_finalizedtransac.add(jtxt_payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 280, -1));

        jbtn_backrentinfo.setText("back");
        jbtn_backrentinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_backrentinfoActionPerformed(evt);
            }
        });
        jpnl_finalizedtransac.add(jbtn_backrentinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 130, -1));

        jbtn_confirm.setText("confirm");
        jbtn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_confirmActionPerformed(evt);
            }
        });
        jpnl_finalizedtransac.add(jbtn_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 130, -1));

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Contract:");
        jpnl_finalizedtransac.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 20));

        getContentPane().add(jpnl_finalizedtransac, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 300, 450));

        jpnl_personalinfo.setBackground(new java.awt.Color(255, 255, 255));
        jpnl_personalinfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(220, 220, 220));
        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PERSONAL INFO");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setOpaque(true);
        jpnl_personalinfo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        jtxt_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_fnameActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jtxt_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 280, -1));

        jtxt_mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_mnameActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jtxt_mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 280, -1));

        jtxt_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_lnameActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jtxt_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 280, -1));

        jtxt_cnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_cnumActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jtxt_cnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 280, -1));

        jtxt_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_mailActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jtxt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 280, -1));

        jtxt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_addressActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jtxt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 280, -1));

        jbtn_govidupload.setText("upload");
        jbtn_govidupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_goviduploadActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jbtn_govidupload, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 130, 30));

        jlbl_govid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnl_personalinfo.add(jlbl_govid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 220, 20));

        jbtn_cancel.setText("cancel");
        jbtn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jbtn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 130, -1));

        jbtn_torentinfo.setText("next");
        jbtn_torentinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_torentinfoActionPerformed(evt);
            }
        });
        jpnl_personalinfo.add(jbtn_torentinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 130, -1));

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Valid ID:");
        jpnl_personalinfo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 20));

        getContentPane().add(jpnl_personalinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_fnameActionPerformed

    private void jtxt_mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_mnameActionPerformed

    private void jtxt_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_lnameActionPerformed

    private void jtxt_cnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_cnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_cnumActionPerformed

    private void jtxt_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_mailActionPerformed

    private void jtxt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_addressActionPerformed

    private void jbtn_goviduploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_goviduploadActionPerformed

         JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String fileName = f.getAbsolutePath();
        
        jlbl_govid.setText(fileName.substring(fileName.lastIndexOf('\\')+1));
        
        File file = new File(fileName);
        FileInputStream fis;
        
        try {
            fis = new FileInputStream(file);
            
            fis = new FileInputStream(file);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[]buf = new byte [1024];
            for(int readNum; (readNum = fis.read(buf)) != -1;){
                bos.write(buf, 0, readNum);
            }
           uploadedDocu = bos.toByteArray();
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(addrenter.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(addrenter.class.getName()).log(Level.SEVERE, null, ex);
        }





    }//GEN-LAST:event_jbtn_goviduploadActionPerformed

    private void jbtn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelActionPerformed

        this.dispose();

    }//GEN-LAST:event_jbtn_cancelActionPerformed

    private void jbtn_torentinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_torentinfoActionPerformed

       if(jtxt_fname.getText().isEmpty() || jtxt_mname.getText().isEmpty() || jtxt_lname.getText().isEmpty()
         || jtxt_cnum.getText().isEmpty() || jtxt_mail.getText().isEmpty() || jtxt_address.getText().isEmpty()
         || jlbl_govid.getText().equals("Valid ID")){
            
            JOptionPane.showMessageDialog(this, "Please do not add Blank Spaces");
       }else{
            
            personalInfo.add(jtxt_fname.getText());
            personalInfo.add(jtxt_mname.getText());
            personalInfo.add(jtxt_lname.getText());
            personalInfo.add(jtxt_cnum.getText());
            personalInfo.add(jtxt_mail.getText());
            personalInfo.add(jtxt_address.getText());
        
        
        this.setSize(615, 490);
        this.setLocationRelativeTo(null);
        this.revalidate(); //refresh main/frame
        this.repaint();

        disableComponents(jpnl_personalinfo, false);
        
       }

    }//GEN-LAST:event_jbtn_torentinfoActionPerformed

    private void jtxt_duedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_duedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_duedateActionPerformed

    private void jtxt_eventinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_eventinfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_eventinfoActionPerformed

    private void jbtn_totransumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_totransumActionPerformed

        if(equipinfo.get(0).isEmpty()||
                jtxt_Quantity.getText().isEmpty()||
                jtxt_duedate.getText().isEmpty()||
                jtxt_eventinfo.getText().isEmpty()){
            
            
                JOptionPane.showMessageDialog(this, "no blank spaces");
           
        } else {
    
            rentquantity = Integer.parseInt(jtxt_Quantity.getText());
            if(equipquantity >= rentquantity){

                    duedate = LocalDate.parse(jtxt_duedate.getText(), formatter);
                    eventinfo = jtxt_eventinfo.getText();

                    long totalrentingdays = ChronoUnit.DAYS.between(LocalDate.parse(borroweddate, formatter), duedate);

                    totalpayable = (rentquantity * equiprentingprice) * totalrentingdays;
                    System.out.println(totalrentingdays);
                    System.out.println(equiprentingprice);
                    System.out.println(rentquantity);

                    JOptionPane.showMessageDialog(this, "total payable: " + totalpayable);

                }else{

                    JOptionPane.showMessageDialog(this, equipinfo.get(2) + " current have " + equipinfo.get(5) + "stocks/s");


                }


                this.setSize(915, 490);
                this.setLocationRelativeTo(null);
                this.revalidate(); //refresh main/frame
                this.repaint();




                disableComponents(jpnl_rentinginfo, false);
    
        }
        
        transummary ();
        
    }//GEN-LAST:event_jbtn_totransumActionPerformed

    private void jbtn_backpersonalinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_backpersonalinfoActionPerformed

        this.setSize(315, 490);
        this.setLocationRelativeTo(null);
        this.revalidate(); //refresh main/frame
        this.repaint();

        disableComponents(jpnl_personalinfo, true);



             

    }//GEN-LAST:event_jbtn_backpersonalinfoActionPerformed

    private void jbtn_uploadcontractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_uploadcontractActionPerformed

JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String fileName = f.getAbsolutePath();
        
        jlbl_contract.setText(fileName.substring(fileName.lastIndexOf('\\')+1));
        
        File file = new File(fileName);
        FileInputStream fis;
        
        try {
            fis = new FileInputStream(file);
            
            fis = new FileInputStream(file);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[]buf = new byte [1024];
            for(int readNum; (readNum = fis.read(buf)) != -1;){
                bos.write(buf, 0, readNum);
            }
           contractfile = bos.toByteArray();
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(addrenter.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(addrenter.class.getName()).log(Level.SEVERE, null, ex);
        }







    }//GEN-LAST:event_jbtn_uploadcontractActionPerformed

    private void jtxt_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_paymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_paymentActionPerformed

    private void jbtn_backrentinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_backrentinfoActionPerformed

        this.setSize(615, 490);
        this.setLocationRelativeTo(null);
        this.revalidate(); //refresh main/frame
        this.repaint();
        
        disableComponents(jpnl_rentinginfo, true);

    }//GEN-LAST:event_jbtn_backrentinfoActionPerformed

    
    
    
    
    
    
    
    private void jbtn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_confirmActionPerformed

        boolean addrenterstate = true;
        
        if(jlbl_contract.getText().equals("Renting contract") || totalpayable > Integer.parseInt(jtxt_payment.getText())){
            
            JOptionPane.showMessageDialog(this, "please input valid info");
            
        }else{
            
            String addrenter = "INSERT INTO renter_info(first_name, middle_name, last_name, contact_no, email, address, valid_id)"
                    + "VALUES (?,?,?,?,?,?,?)";
        
            try {
                pts = DBConnect.getInstance().con.prepareStatement(addrenter);
                
                pts.setString(1, personalInfo.get(0));
                pts.setString(2, personalInfo.get(1));
                pts.setString(3, personalInfo.get(2));
                pts.setString(4, personalInfo.get(3));
                pts.setString(5, personalInfo.get(4));
                pts.setString(6, personalInfo.get(4));
                pts.setBytes(7,  uploadedDocu);
                
                 addrenterstate = pts.execute();
                
            } catch (SQLException ex) {
                Logger.getLogger(addrenter.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
            if(addrenterstate == false){
            
            
            
            String renterID = null;
            String getrenterID = "SELECT MAX (renter_ID) FROM renter_info";
            
            try {
                pts= DBConnect.getInstance().con.prepareStatement(getrenterID);
                
                rs = pts.executeQuery();
                renterID = rs.getString(1);
                
            } catch (SQLException ex) {
                Logger.getLogger(addrenter.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            
            
            
            
            
            String addrentinfo = "INSERT INTO rent_info (renter_id, category_name, model_id, borrowed_date, due_date, event_info, quantity, total_payable, contract_type,status) VALUES(?,?,?,?,?,?,?,?,?,?)";
            
            
            try {
                pts = DBConnect.getInstance().con.prepareStatement(addrentinfo);
                
                pts.setString(1, renterID);
                pts.setString(2, equipinfo.get(1));
                pts.setString(3, equipinfo.get(1));
                pts.setString(4, borroweddate);
                pts.setString(5, duedate.toString());
                pts.setString(6, eventinfo);
                pts.setInt(7, rentquantity);
                pts.setDouble(8, totalpayable);
                pts.setBytes(9, contractfile);
                pts.setString(10, "Ongoing");
                
                boolean addRentState = pts.execute();
                
                if(addRentState == false){
                
                    JOptionPane.showMessageDialog(this, "Transaction confirmed \n" + "Change: P" + (Double.parseDouble(jtxt_payment.getText()) - totalpayable));
                
                    personalInfo.clear();;
                    equipinfo.clear();
                    
                    jtxa_transummary.setText("");
                    jtxa_spec.setText("");
                    
                    jlbl_govid.setText("Valid ID");
                    jlbl_contract.setText("renting contract");
                    
                    jtxt_payment.setText("");
                    jtxt_Quantity.setText("");
                    jtxt_eventinfo.setText("");
                    jtxt_duedate.setText("");
                    
                    jtxt_fname.setText("");
                    jtxt_lname.setText("");
                    jtxt_mname.setText("");
                    jtxt_cnum.setText("");
                    jtxt_mail.setText("");
                    jtxt_address.setText("");
                    
                    this.dispose();
                }
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(addrenter.class.getName()).log(Level.SEVERE, null, ex);
            }
          }
        }

    }//GEN-LAST:event_jbtn_confirmActionPerformed

    //EXAM --- AFTER CLICKING CONFIRM A THE TABLE SHOULD BE POPULATED. SORT (ONGOING-) ALL. ONGOING. TASK. DUE. CATEGORY (ONGOING/ PAST DUE. CATEGORY)
    // NEXT WEEK --- EDIT INFO
    
    
    
    
    
    
    
    
    
    
    private void jtxt_QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_QuantityActionPerformed

    
    
    
    //------------------- ASSIGNEMENT-PLACE HOLDERS: FINISHED
    
    public void disableComponents(JPanel currentPanel, boolean isEnabled){
        
        currentPanel.setEnabled(isEnabled);
        Component[] components = currentPanel.getComponents();
        
        for(Component comp : components){
        
            if (comp instanceof JPanel){
            
                disableComponents((JPanel)comp, isEnabled);
                
            }
            comp.setEnabled(isEnabled);    
        }

    }
    
    
    
    
    
    
    public void comboActionListeners(){
    
        jcmb_category.addActionListener(e->{
            
            jcmb_equipment.removeAllItems();
            
            String getEquipment = "SELECT model_id FROM equipment_info WHERE category_name = '" + jcmb_category.getSelectedItem().toString() +"' ";
           
            
            try {
                pts = DBConnect.getInstance().con.prepareStatement(getEquipment);
                rs = pts.executeQuery();
                
                while(rs.next()){
                    jcmb_equipment.addItem(rs.getString(1));
                }
                
                
            } catch (SQLException ex) {
                Logger.getLogger(addrenter.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            //comboActionListeners();
            
        });
        
        
        
        
        
        //JCOMBO BOX EQUIPMENT IS NOT POPULATED---------------------------------
        
        jcmb_equipment.addActionListener(e->{
            
            if(jcmb_equipment.getSelectedItem() == null){
            
            //jcmb_equipment.removeAllItems();
            
            }else{
            
            String getEquipment = "SELECT * FROM equipment_info WHERE model_id = '" + jcmb_equipment.getSelectedItem().toString() + "' ";
           
            
            try {
                pts = DBConnect.getInstance().con.prepareStatement(getEquipment);
                equiprs = pts.executeQuery();
                
               equipinfo.clear();
                
                equipinfo.add(equiprs.getString(1));
                equipinfo.add(equiprs.getString(2));
                equipinfo.add(equiprs.getString(3));
                equipinfo.add(equiprs.getString(4));
                equipImage = equiprs.getBytes(5);
                equipinfo.add(equiprs.getString(6));
                
                equipinfo.add(Integer.toString(equiprs.getInt(7)));
                equipquantity = equiprs.getInt(7);
                
                equipinfo.add(Double.toString(equiprs.getDouble(8)));
                equiprentingprice = equiprs.getDouble(8);
                
                jtxa_spec.setText(equiprs.getString(6));
                
                ImageIcon image = new ImageIcon(equipImage);
                Image imageScale = image.getImage();
                Image imageScaled = imageScale.getScaledInstance(jlbl_equipimage.getWidth(), jlbl_equipimage.getHeight(), Image.SCALE_SMOOTH);
                
                image = new ImageIcon(imageScaled);
                jlbl_equipimage.setIcon(image);
                 

                
                
            } catch (SQLException ex) {
                Logger.getLogger(addrenter.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            
        });
        
        
    
    
    
    
    }
    
    
    
    
    public void transummary (){
    
        jtxa_transummary.setText(
        
        "PERSONAL INFO INFORMATION ----------------------\n"
                
                
                
                + "FULL NAME:      " + personalInfo.get(2) +  ", " + personalInfo.get(0) +  ", " + personalInfo.get(1) + "\n"
                + "CONTACT NUMBER: " + personalInfo.get(3) + "\n"
                + "GMAIL:          " + personalInfo.get(4) + "\n"       
                + "ADDRESS:        " + personalInfo.get(5) + "\n \n"       
        
                        
                        
        + "EQUIPMENT INFORMATION ----------------------\n" 
                

                + "MODEL ID:        " + equipinfo.get(0) + "\n"
                + "EQUIPMENST NAME: " + equipinfo.get(2) + "\n"
                + "BRAND NAME:      " + equipinfo.get(3) + "\n"
                + "SPECIFICATIONS:  " + equipinfo.get(4) + "\n"
                + "RENTING PRICE:   " + equipinfo.get(6) + "\n \n"
                
                
        + "RENTING INFORMATION ----------------------\n" 
                
                +"BORROWED DATE:     " + borroweddate + "\n"
                +"DUE DATE:          " + duedate + "\n"
                + "QUANTITY:         " + rentquantity + "\n"
                + "TOTAY PAYABLE: " + totalpayable + "\n"
        
        
        );
    
    
    }
    
    
    
    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addrenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addrenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addrenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addrenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addrenter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JButton jbtn_backpersonalinfo;
    private javax.swing.JButton jbtn_backrentinfo;
    private javax.swing.JButton jbtn_cancel;
    private javax.swing.JButton jbtn_confirm;
    private javax.swing.JButton jbtn_govidupload;
    private javax.swing.JButton jbtn_torentinfo;
    private javax.swing.JButton jbtn_totransum;
    private javax.swing.JButton jbtn_uploadcontract;
    private javax.swing.JComboBox<String> jcmb_category;
    private javax.swing.JComboBox<String> jcmb_equipment;
    private javax.swing.JLabel jlbl_borroweddate;
    private javax.swing.JLabel jlbl_contract;
    private javax.swing.JLabel jlbl_equipimage;
    private javax.swing.JLabel jlbl_govid;
    private javax.swing.JPanel jpnl_finalizedtransac;
    private javax.swing.JPanel jpnl_personalinfo;
    private javax.swing.JPanel jpnl_rentinginfo;
    private javax.swing.JTextArea jtxa_spec;
    private javax.swing.JTextArea jtxa_transummary;
    private javax.swing.JTextField jtxt_Quantity;
    private javax.swing.JTextField jtxt_address;
    private javax.swing.JTextField jtxt_cnum;
    private javax.swing.JTextField jtxt_duedate;
    private javax.swing.JTextField jtxt_eventinfo;
    private javax.swing.JTextField jtxt_fname;
    private javax.swing.JTextField jtxt_lname;
    private javax.swing.JTextField jtxt_mail;
    private javax.swing.JTextField jtxt_mname;
    private javax.swing.JTextField jtxt_payment;
    // End of variables declaration//GEN-END:variables
}
